version: "3"

services:
  redis:
    image: 'redis:6.2.2'
    restart: always
    hostname: redis
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass password
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5672:5672"
      - "15672:15672" 
  authentication:
    build: 
      context: ../
      dockerfile: auth.Dockerfile
    restart: always
    ports:
        - "5555:5555"
    links:
        - "redis:myredis"
        - "rabbitmq:myrabbit"
  billing:
    build: 
      context: ../
      dockerfile: bills.Dockerfile
    restart: always
    ports:
        - "7777:7777"
    links:
        - "redis:myredis"
        - "rabbitmq:myrabbit"
