// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.8
// source: models/v1/billing.proto

package models

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Bill_PayingWith int32

const (
	Bill_LOAN     Bill_PayingWith = 0
	Bill_MYSELF   Bill_PayingWith = 1
	Bill_EXTERNAL Bill_PayingWith = 2
)

// Enum value maps for Bill_PayingWith.
var (
	Bill_PayingWith_name = map[int32]string{
		0: "LOAN",
		1: "MYSELF",
		2: "EXTERNAL",
	}
	Bill_PayingWith_value = map[string]int32{
		"LOAN":     0,
		"MYSELF":   1,
		"EXTERNAL": 2,
	}
)

func (x Bill_PayingWith) Enum() *Bill_PayingWith {
	p := new(Bill_PayingWith)
	*p = x
	return p
}

func (x Bill_PayingWith) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Bill_PayingWith) Descriptor() protoreflect.EnumDescriptor {
	return file_models_v1_billing_proto_enumTypes[0].Descriptor()
}

func (Bill_PayingWith) Type() protoreflect.EnumType {
	return &file_models_v1_billing_proto_enumTypes[0]
}

func (x Bill_PayingWith) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Bill_PayingWith.Descriptor instead.
func (Bill_PayingWith) EnumDescriptor() ([]byte, []int) {
	return file_models_v1_billing_proto_rawDescGZIP(), []int{7, 0}
}

type Biller struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CardToken string `protobuf:"bytes,2,opt,name=card_token,json=cardToken,proto3" json:"card_token,omitempty"`
	Cart      string `protobuf:"bytes,3,opt,name=cart,proto3" json:"cart,omitempty"`
	CreatedAt int64  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt int64  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt int64  `protobuf:"varint,9,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
}

func (x *Biller) Reset() {
	*x = Biller{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_v1_billing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Biller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Biller) ProtoMessage() {}

func (x *Biller) ProtoReflect() protoreflect.Message {
	mi := &file_models_v1_billing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Biller.ProtoReflect.Descriptor instead.
func (*Biller) Descriptor() ([]byte, []int) {
	return file_models_v1_billing_proto_rawDescGZIP(), []int{0}
}

func (x *Biller) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Biller) GetCardToken() string {
	if x != nil {
		return x.CardToken
	}
	return ""
}

func (x *Biller) GetCart() string {
	if x != nil {
		return x.Cart
	}
	return ""
}

func (x *Biller) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Biller) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Biller) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

type UpdateBillerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Old *Biller `protobuf:"bytes,1,opt,name=old,proto3" json:"old,omitempty"`
	New *Biller `protobuf:"bytes,2,opt,name=new,proto3" json:"new,omitempty"`
}

func (x *UpdateBillerRequest) Reset() {
	*x = UpdateBillerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_v1_billing_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBillerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBillerRequest) ProtoMessage() {}

func (x *UpdateBillerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_v1_billing_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBillerRequest.ProtoReflect.Descriptor instead.
func (*UpdateBillerRequest) Descriptor() ([]byte, []int) {
	return file_models_v1_billing_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateBillerRequest) GetOld() *Biller {
	if x != nil {
		return x.Old
	}
	return nil
}

func (x *UpdateBillerRequest) GetNew() *Biller {
	if x != nil {
		return x.New
	}
	return nil
}

type BillerCreatedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BillerCreatedResponse) Reset() {
	*x = BillerCreatedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_v1_billing_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BillerCreatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillerCreatedResponse) ProtoMessage() {}

func (x *BillerCreatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_v1_billing_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillerCreatedResponse.ProtoReflect.Descriptor instead.
func (*BillerCreatedResponse) Descriptor() ([]byte, []int) {
	return file_models_v1_billing_proto_rawDescGZIP(), []int{2}
}

func (x *BillerCreatedResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BillCategory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string  `protobuf:"bytes,10,opt,name=id,proto3" json:"id,omitempty"`
	RefTitle        string  `protobuf:"bytes,2,opt,name=refTitle,proto3" json:"refTitle,omitempty"`
	DisplayTitle    string  `protobuf:"bytes,3,opt,name=displayTitle,proto3" json:"displayTitle,omitempty"`
	CurrentDiscount float32 `protobuf:"fixed32,4,opt,name=currentDiscount,proto3" json:"currentDiscount,omitempty"`
	Active          bool    `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt       int64   `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       int64   `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *BillCategory) Reset() {
	*x = BillCategory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_v1_billing_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BillCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillCategory) ProtoMessage() {}

func (x *BillCategory) ProtoReflect() protoreflect.Message {
	mi := &file_models_v1_billing_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillCategory.ProtoReflect.Descriptor instead.
func (*BillCategory) Descriptor() ([]byte, []int) {
	return file_models_v1_billing_proto_rawDescGZIP(), []int{3}
}

func (x *BillCategory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BillCategory) GetRefTitle() string {
	if x != nil {
		return x.RefTitle
	}
	return ""
}

func (x *BillCategory) GetDisplayTitle() string {
	if x != nil {
		return x.DisplayTitle
	}
	return ""
}

func (x *BillCategory) GetCurrentDiscount() float32 {
	if x != nil {
		return x.CurrentDiscount
	}
	return 0
}

func (x *BillCategory) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *BillCategory) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *BillCategory) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type BillCategoryCreatedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BillCategoryCreatedResponse) Reset() {
	*x = BillCategoryCreatedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_v1_billing_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BillCategoryCreatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillCategoryCreatedResponse) ProtoMessage() {}

func (x *BillCategoryCreatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_v1_billing_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillCategoryCreatedResponse.ProtoReflect.Descriptor instead.
func (*BillCategoryCreatedResponse) Descriptor() ([]byte, []int) {
	return file_models_v1_billing_proto_rawDescGZIP(), []int{4}
}

func (x *BillCategoryCreatedResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateBillCategoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Old *BillCategory `protobuf:"bytes,1,opt,name=old,proto3" json:"old,omitempty"`
	New *BillCategory `protobuf:"bytes,2,opt,name=new,proto3" json:"new,omitempty"`
}

func (x *UpdateBillCategoryRequest) Reset() {
	*x = UpdateBillCategoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_v1_billing_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBillCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBillCategoryRequest) ProtoMessage() {}

func (x *UpdateBillCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_v1_billing_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBillCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateBillCategoryRequest) Descriptor() ([]byte, []int) {
	return file_models_v1_billing_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateBillCategoryRequest) GetOld() *BillCategory {
	if x != nil {
		return x.Old
	}
	return nil
}

func (x *UpdateBillCategoryRequest) GetNew() *BillCategory {
	if x != nil {
		return x.New
	}
	return nil
}

type BillCategoriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Categories []*BillCategory `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
}

func (x *BillCategoriesResponse) Reset() {
	*x = BillCategoriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_v1_billing_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BillCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillCategoriesResponse) ProtoMessage() {}

func (x *BillCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_v1_billing_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillCategoriesResponse.ProtoReflect.Descriptor instead.
func (*BillCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_models_v1_billing_proto_rawDescGZIP(), []int{6}
}

func (x *BillCategoriesResponse) GetCategories() []*BillCategory {
	if x != nil {
		return x.Categories
	}
	return nil
}

type Bill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cart            string          `protobuf:"bytes,2,opt,name=cart,proto3" json:"cart,omitempty"`
	Title           string          `protobuf:"bytes,10,opt,name=title,proto3" json:"title,omitempty"`
	Reoccurring     bool            `protobuf:"varint,3,opt,name=reoccurring,proto3" json:"reoccurring,omitempty"`
	NextPaymentDate int64           `protobuf:"varint,4,opt,name=nextPaymentDate,proto3" json:"nextPaymentDate,omitempty"`
	Active          bool            `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	PayingWith      Bill_PayingWith `protobuf:"varint,6,opt,name=payingWith,proto3,enum=models.Bill_PayingWith" json:"payingWith,omitempty"`
	CreatedAt       int64           `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       int64           `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt       int64           `protobuf:"varint,9,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
}

func (x *Bill) Reset() {
	*x = Bill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_v1_billing_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bill) ProtoMessage() {}

func (x *Bill) ProtoReflect() protoreflect.Message {
	mi := &file_models_v1_billing_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bill.ProtoReflect.Descriptor instead.
func (*Bill) Descriptor() ([]byte, []int) {
	return file_models_v1_billing_proto_rawDescGZIP(), []int{7}
}

func (x *Bill) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bill) GetCart() string {
	if x != nil {
		return x.Cart
	}
	return ""
}

func (x *Bill) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Bill) GetReoccurring() bool {
	if x != nil {
		return x.Reoccurring
	}
	return false
}

func (x *Bill) GetNextPaymentDate() int64 {
	if x != nil {
		return x.NextPaymentDate
	}
	return 0
}

func (x *Bill) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Bill) GetPayingWith() Bill_PayingWith {
	if x != nil {
		return x.PayingWith
	}
	return Bill_LOAN
}

func (x *Bill) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Bill) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Bill) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

type GetBillerBillsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BillerID string `protobuf:"bytes,1,opt,name=billerID,proto3" json:"billerID,omitempty"`
}

func (x *GetBillerBillsRequest) Reset() {
	*x = GetBillerBillsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_v1_billing_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBillerBillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillerBillsRequest) ProtoMessage() {}

func (x *GetBillerBillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_v1_billing_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillerBillsRequest.ProtoReflect.Descriptor instead.
func (*GetBillerBillsRequest) Descriptor() ([]byte, []int) {
	return file_models_v1_billing_proto_rawDescGZIP(), []int{8}
}

func (x *GetBillerBillsRequest) GetBillerID() string {
	if x != nil {
		return x.BillerID
	}
	return ""
}

type BillsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bills []*Bill `protobuf:"bytes,1,rep,name=bills,proto3" json:"bills,omitempty"`
}

func (x *BillsResponse) Reset() {
	*x = BillsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_v1_billing_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillsResponse) ProtoMessage() {}

func (x *BillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_v1_billing_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillsResponse.ProtoReflect.Descriptor instead.
func (*BillsResponse) Descriptor() ([]byte, []int) {
	return file_models_v1_billing_proto_rawDescGZIP(), []int{9}
}

func (x *BillsResponse) GetBills() []*Bill {
	if x != nil {
		return x.Bills
	}
	return nil
}

type BillCreatedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BillCreatedResponse) Reset() {
	*x = BillCreatedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_v1_billing_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BillCreatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillCreatedResponse) ProtoMessage() {}

func (x *BillCreatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_v1_billing_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillCreatedResponse.ProtoReflect.Descriptor instead.
func (*BillCreatedResponse) Descriptor() ([]byte, []int) {
	return file_models_v1_billing_proto_rawDescGZIP(), []int{10}
}

func (x *BillCreatedResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateBillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Old *Bill `protobuf:"bytes,1,opt,name=old,proto3" json:"old,omitempty"`
	New *Bill `protobuf:"bytes,2,opt,name=new,proto3" json:"new,omitempty"`
}

func (x *UpdateBillRequest) Reset() {
	*x = UpdateBillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_v1_billing_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBillRequest) ProtoMessage() {}

func (x *UpdateBillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_v1_billing_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBillRequest.ProtoReflect.Descriptor instead.
func (*UpdateBillRequest) Descriptor() ([]byte, []int) {
	return file_models_v1_billing_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateBillRequest) GetOld() *Bill {
	if x != nil {
		return x.Old
	}
	return nil
}

func (x *UpdateBillRequest) GetNew() *Bill {
	if x != nil {
		return x.New
	}
	return nil
}

var File_models_v1_billing_proto protoreflect.FileDescriptor

var file_models_v1_billing_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x69, 0x6c, 0x6c,
	0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa8,
	0x01, 0x0a, 0x06, 0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x72,
	0x64, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63,
	0x61, 0x72, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x61, 0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x59, 0x0a, 0x13, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x20, 0x0a, 0x03, 0x6f, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x03, 0x6f,
	0x6c, 0x64, 0x12, 0x20, 0x0a, 0x03, 0x6e, 0x65, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x52,
	0x03, 0x6e, 0x65, 0x77, 0x22, 0x27, 0x0a, 0x15, 0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xde, 0x01,
	0x0a, 0x0c, 0x42, 0x69, 0x6c, 0x6c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x65, 0x66, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x72, 0x65, 0x66, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x69,
	0x73, 0x70, 0x6c, 0x61, 0x79, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x28,
	0x0a, 0x0f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x2d,
	0x0a, 0x1b, 0x42, 0x69, 0x6c, 0x6c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x6b, 0x0a,
	0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x03, 0x6f, 0x6c,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x03, 0x6f,
	0x6c, 0x64, 0x12, 0x26, 0x0a, 0x03, 0x6e, 0x65, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x03, 0x6e, 0x65, 0x77, 0x22, 0x4e, 0x0a, 0x16, 0x42, 0x69,
	0x6c, 0x6c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x0a,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x22, 0xec, 0x02, 0x0a, 0x04, 0x42,
	0x69, 0x6c, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x61, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x72, 0x65, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0b, 0x72, 0x65, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x69, 0x6e, 0x67, 0x12,
	0x28, 0x0a, 0x0f, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61,
	0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x12, 0x37, 0x0a, 0x0a, 0x70, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x57, 0x69, 0x74, 0x68, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42,
	0x69, 0x6c, 0x6c, 0x2e, 0x50, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x57, 0x69, 0x74, 0x68, 0x52, 0x0a,
	0x70, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x57, 0x69, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x30, 0x0a, 0x0a, 0x50, 0x61, 0x79, 0x69, 0x6e,
	0x67, 0x57, 0x69, 0x74, 0x68, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x4f, 0x41, 0x4e, 0x10, 0x00, 0x12,
	0x0a, 0x0a, 0x06, 0x4d, 0x59, 0x53, 0x45, 0x4c, 0x46, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x45,
	0x58, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x10, 0x02, 0x22, 0x33, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x42, 0x69, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x44, 0x22, 0x33,
	0x0a, 0x0d, 0x42, 0x69, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x22, 0x0a, 0x05, 0x62, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x05, 0x62, 0x69,
	0x6c, 0x6c, 0x73, 0x22, 0x25, 0x0a, 0x13, 0x42, 0x69, 0x6c, 0x6c, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x53, 0x0a, 0x11, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1e, 0x0a, 0x03, 0x6f, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x03, 0x6f, 0x6c, 0x64, 0x12,
	0x1e, 0x0a, 0x03, 0x6e, 0x65, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x03, 0x6e, 0x65, 0x77, 0x32,
	0xe0, 0x05, 0x0a, 0x13, 0x4e, 0x61, 0x65, 0x72, 0x61, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x0e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x1a, 0x1d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x0a, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x69,
	0x6c, 0x6c, 0x65, 0x72, 0x12, 0x0e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x69,
	0x6c, 0x6c, 0x65, 0x72, 0x1a, 0x0e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x69,
	0x6c, 0x6c, 0x65, 0x72, 0x12, 0x43, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x69,
	0x6c, 0x6c, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x46, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x42, 0x69, 0x6c, 0x6c, 0x73, 0x12, 0x1d, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x42, 0x69,
	0x6c, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x37, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x12,
	0x0c, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x1a, 0x1b, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x08, 0x46, 0x69,
	0x6e, 0x64, 0x42, 0x69, 0x6c, 0x6c, 0x12, 0x0c, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e,
	0x42, 0x69, 0x6c, 0x6c, 0x1a, 0x0c, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x69,
	0x6c, 0x6c, 0x12, 0x3f, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c,
	0x12, 0x19, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x4b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x1e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4f, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x14, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e,
	0x42, 0x69, 0x6c, 0x6c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x1a, 0x23, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3e, 0x0a, 0x10, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x69, 0x6c, 0x6c, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x14, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42,
	0x69, 0x6c, 0x6c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x1a, 0x14, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x12, 0x4f, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x21, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_v1_billing_proto_rawDescOnce sync.Once
	file_models_v1_billing_proto_rawDescData = file_models_v1_billing_proto_rawDesc
)

func file_models_v1_billing_proto_rawDescGZIP() []byte {
	file_models_v1_billing_proto_rawDescOnce.Do(func() {
		file_models_v1_billing_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_v1_billing_proto_rawDescData)
	})
	return file_models_v1_billing_proto_rawDescData
}

var file_models_v1_billing_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_models_v1_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_models_v1_billing_proto_goTypes = []interface{}{
	(Bill_PayingWith)(0),                // 0: models.Bill.PayingWith
	(*Biller)(nil),                      // 1: models.Biller
	(*UpdateBillerRequest)(nil),         // 2: models.UpdateBillerRequest
	(*BillerCreatedResponse)(nil),       // 3: models.BillerCreatedResponse
	(*BillCategory)(nil),                // 4: models.BillCategory
	(*BillCategoryCreatedResponse)(nil), // 5: models.BillCategoryCreatedResponse
	(*UpdateBillCategoryRequest)(nil),   // 6: models.UpdateBillCategoryRequest
	(*BillCategoriesResponse)(nil),      // 7: models.BillCategoriesResponse
	(*Bill)(nil),                        // 8: models.Bill
	(*GetBillerBillsRequest)(nil),       // 9: models.GetBillerBillsRequest
	(*BillsResponse)(nil),               // 10: models.BillsResponse
	(*BillCreatedResponse)(nil),         // 11: models.BillCreatedResponse
	(*UpdateBillRequest)(nil),           // 12: models.UpdateBillRequest
	(*empty.Empty)(nil),                 // 13: google.protobuf.Empty
}
var file_models_v1_billing_proto_depIdxs = []int32{
	1,  // 0: models.UpdateBillerRequest.old:type_name -> models.Biller
	1,  // 1: models.UpdateBillerRequest.new:type_name -> models.Biller
	4,  // 2: models.UpdateBillCategoryRequest.old:type_name -> models.BillCategory
	4,  // 3: models.UpdateBillCategoryRequest.new:type_name -> models.BillCategory
	4,  // 4: models.BillCategoriesResponse.categories:type_name -> models.BillCategory
	0,  // 5: models.Bill.payingWith:type_name -> models.Bill.PayingWith
	8,  // 6: models.BillsResponse.bills:type_name -> models.Bill
	8,  // 7: models.UpdateBillRequest.old:type_name -> models.Bill
	8,  // 8: models.UpdateBillRequest.new:type_name -> models.Bill
	1,  // 9: models.NaeraBillingService.CreateBiller:input_type -> models.Biller
	1,  // 10: models.NaeraBillingService.FindBiller:input_type -> models.Biller
	2,  // 11: models.NaeraBillingService.UpdateBiller:input_type -> models.UpdateBillerRequest
	9,  // 12: models.NaeraBillingService.GetBillerBills:input_type -> models.GetBillerBillsRequest
	8,  // 13: models.NaeraBillingService.CreateBill:input_type -> models.Bill
	8,  // 14: models.NaeraBillingService.FindBill:input_type -> models.Bill
	12, // 15: models.NaeraBillingService.UpdateBill:input_type -> models.UpdateBillRequest
	13, // 16: models.NaeraBillingService.GetBillCategories:input_type -> google.protobuf.Empty
	4,  // 17: models.NaeraBillingService.CreateBillCategory:input_type -> models.BillCategory
	4,  // 18: models.NaeraBillingService.FindBillCategory:input_type -> models.BillCategory
	6,  // 19: models.NaeraBillingService.UpdateBillCategory:input_type -> models.UpdateBillCategoryRequest
	3,  // 20: models.NaeraBillingService.CreateBiller:output_type -> models.BillerCreatedResponse
	1,  // 21: models.NaeraBillingService.FindBiller:output_type -> models.Biller
	13, // 22: models.NaeraBillingService.UpdateBiller:output_type -> google.protobuf.Empty
	10, // 23: models.NaeraBillingService.GetBillerBills:output_type -> models.BillsResponse
	11, // 24: models.NaeraBillingService.CreateBill:output_type -> models.BillCreatedResponse
	8,  // 25: models.NaeraBillingService.FindBill:output_type -> models.Bill
	13, // 26: models.NaeraBillingService.UpdateBill:output_type -> google.protobuf.Empty
	7,  // 27: models.NaeraBillingService.GetBillCategories:output_type -> models.BillCategoriesResponse
	5,  // 28: models.NaeraBillingService.CreateBillCategory:output_type -> models.BillCategoryCreatedResponse
	4,  // 29: models.NaeraBillingService.FindBillCategory:output_type -> models.BillCategory
	13, // 30: models.NaeraBillingService.UpdateBillCategory:output_type -> google.protobuf.Empty
	20, // [20:31] is the sub-list for method output_type
	9,  // [9:20] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_models_v1_billing_proto_init() }
func file_models_v1_billing_proto_init() {
	if File_models_v1_billing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_models_v1_billing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Biller); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_v1_billing_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBillerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_v1_billing_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BillerCreatedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_v1_billing_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BillCategory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_v1_billing_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BillCategoryCreatedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_v1_billing_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBillCategoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_v1_billing_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BillCategoriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_v1_billing_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_v1_billing_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBillerBillsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_v1_billing_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BillsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_v1_billing_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BillCreatedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_v1_billing_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_v1_billing_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_models_v1_billing_proto_goTypes,
		DependencyIndexes: file_models_v1_billing_proto_depIdxs,
		EnumInfos:         file_models_v1_billing_proto_enumTypes,
		MessageInfos:      file_models_v1_billing_proto_msgTypes,
	}.Build()
	File_models_v1_billing_proto = out.File
	file_models_v1_billing_proto_rawDesc = nil
	file_models_v1_billing_proto_goTypes = nil
	file_models_v1_billing_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NaeraBillingServiceClient is the client API for NaeraBillingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NaeraBillingServiceClient interface {
	CreateBiller(ctx context.Context, in *Biller, opts ...grpc.CallOption) (*BillerCreatedResponse, error)
	FindBiller(ctx context.Context, in *Biller, opts ...grpc.CallOption) (*Biller, error)
	UpdateBiller(ctx context.Context, in *UpdateBillerRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetBillerBills(ctx context.Context, in *GetBillerBillsRequest, opts ...grpc.CallOption) (*BillsResponse, error)
	CreateBill(ctx context.Context, in *Bill, opts ...grpc.CallOption) (*BillCreatedResponse, error)
	FindBill(ctx context.Context, in *Bill, opts ...grpc.CallOption) (*Bill, error)
	UpdateBill(ctx context.Context, in *UpdateBillRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetBillCategories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*BillCategoriesResponse, error)
	CreateBillCategory(ctx context.Context, in *BillCategory, opts ...grpc.CallOption) (*BillCategoryCreatedResponse, error)
	FindBillCategory(ctx context.Context, in *BillCategory, opts ...grpc.CallOption) (*BillCategory, error)
	UpdateBillCategory(ctx context.Context, in *UpdateBillCategoryRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type naeraBillingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNaeraBillingServiceClient(cc grpc.ClientConnInterface) NaeraBillingServiceClient {
	return &naeraBillingServiceClient{cc}
}

func (c *naeraBillingServiceClient) CreateBiller(ctx context.Context, in *Biller, opts ...grpc.CallOption) (*BillerCreatedResponse, error) {
	out := new(BillerCreatedResponse)
	err := c.cc.Invoke(ctx, "/models.NaeraBillingService/CreateBiller", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *naeraBillingServiceClient) FindBiller(ctx context.Context, in *Biller, opts ...grpc.CallOption) (*Biller, error) {
	out := new(Biller)
	err := c.cc.Invoke(ctx, "/models.NaeraBillingService/FindBiller", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *naeraBillingServiceClient) UpdateBiller(ctx context.Context, in *UpdateBillerRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/models.NaeraBillingService/UpdateBiller", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *naeraBillingServiceClient) GetBillerBills(ctx context.Context, in *GetBillerBillsRequest, opts ...grpc.CallOption) (*BillsResponse, error) {
	out := new(BillsResponse)
	err := c.cc.Invoke(ctx, "/models.NaeraBillingService/GetBillerBills", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *naeraBillingServiceClient) CreateBill(ctx context.Context, in *Bill, opts ...grpc.CallOption) (*BillCreatedResponse, error) {
	out := new(BillCreatedResponse)
	err := c.cc.Invoke(ctx, "/models.NaeraBillingService/CreateBill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *naeraBillingServiceClient) FindBill(ctx context.Context, in *Bill, opts ...grpc.CallOption) (*Bill, error) {
	out := new(Bill)
	err := c.cc.Invoke(ctx, "/models.NaeraBillingService/FindBill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *naeraBillingServiceClient) UpdateBill(ctx context.Context, in *UpdateBillRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/models.NaeraBillingService/UpdateBill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *naeraBillingServiceClient) GetBillCategories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*BillCategoriesResponse, error) {
	out := new(BillCategoriesResponse)
	err := c.cc.Invoke(ctx, "/models.NaeraBillingService/GetBillCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *naeraBillingServiceClient) CreateBillCategory(ctx context.Context, in *BillCategory, opts ...grpc.CallOption) (*BillCategoryCreatedResponse, error) {
	out := new(BillCategoryCreatedResponse)
	err := c.cc.Invoke(ctx, "/models.NaeraBillingService/CreateBillCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *naeraBillingServiceClient) FindBillCategory(ctx context.Context, in *BillCategory, opts ...grpc.CallOption) (*BillCategory, error) {
	out := new(BillCategory)
	err := c.cc.Invoke(ctx, "/models.NaeraBillingService/FindBillCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *naeraBillingServiceClient) UpdateBillCategory(ctx context.Context, in *UpdateBillCategoryRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/models.NaeraBillingService/UpdateBillCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NaeraBillingServiceServer is the server API for NaeraBillingService service.
type NaeraBillingServiceServer interface {
	CreateBiller(context.Context, *Biller) (*BillerCreatedResponse, error)
	FindBiller(context.Context, *Biller) (*Biller, error)
	UpdateBiller(context.Context, *UpdateBillerRequest) (*empty.Empty, error)
	GetBillerBills(context.Context, *GetBillerBillsRequest) (*BillsResponse, error)
	CreateBill(context.Context, *Bill) (*BillCreatedResponse, error)
	FindBill(context.Context, *Bill) (*Bill, error)
	UpdateBill(context.Context, *UpdateBillRequest) (*empty.Empty, error)
	GetBillCategories(context.Context, *empty.Empty) (*BillCategoriesResponse, error)
	CreateBillCategory(context.Context, *BillCategory) (*BillCategoryCreatedResponse, error)
	FindBillCategory(context.Context, *BillCategory) (*BillCategory, error)
	UpdateBillCategory(context.Context, *UpdateBillCategoryRequest) (*empty.Empty, error)
}

// UnimplementedNaeraBillingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNaeraBillingServiceServer struct {
}

func (*UnimplementedNaeraBillingServiceServer) CreateBiller(context.Context, *Biller) (*BillerCreatedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBiller not implemented")
}
func (*UnimplementedNaeraBillingServiceServer) FindBiller(context.Context, *Biller) (*Biller, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindBiller not implemented")
}
func (*UnimplementedNaeraBillingServiceServer) UpdateBiller(context.Context, *UpdateBillerRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBiller not implemented")
}
func (*UnimplementedNaeraBillingServiceServer) GetBillerBills(context.Context, *GetBillerBillsRequest) (*BillsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBillerBills not implemented")
}
func (*UnimplementedNaeraBillingServiceServer) CreateBill(context.Context, *Bill) (*BillCreatedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBill not implemented")
}
func (*UnimplementedNaeraBillingServiceServer) FindBill(context.Context, *Bill) (*Bill, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindBill not implemented")
}
func (*UnimplementedNaeraBillingServiceServer) UpdateBill(context.Context, *UpdateBillRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBill not implemented")
}
func (*UnimplementedNaeraBillingServiceServer) GetBillCategories(context.Context, *empty.Empty) (*BillCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBillCategories not implemented")
}
func (*UnimplementedNaeraBillingServiceServer) CreateBillCategory(context.Context, *BillCategory) (*BillCategoryCreatedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBillCategory not implemented")
}
func (*UnimplementedNaeraBillingServiceServer) FindBillCategory(context.Context, *BillCategory) (*BillCategory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindBillCategory not implemented")
}
func (*UnimplementedNaeraBillingServiceServer) UpdateBillCategory(context.Context, *UpdateBillCategoryRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBillCategory not implemented")
}

func RegisterNaeraBillingServiceServer(s *grpc.Server, srv NaeraBillingServiceServer) {
	s.RegisterService(&_NaeraBillingService_serviceDesc, srv)
}

func _NaeraBillingService_CreateBiller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Biller)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NaeraBillingServiceServer).CreateBiller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.NaeraBillingService/CreateBiller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NaeraBillingServiceServer).CreateBiller(ctx, req.(*Biller))
	}
	return interceptor(ctx, in, info, handler)
}

func _NaeraBillingService_FindBiller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Biller)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NaeraBillingServiceServer).FindBiller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.NaeraBillingService/FindBiller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NaeraBillingServiceServer).FindBiller(ctx, req.(*Biller))
	}
	return interceptor(ctx, in, info, handler)
}

func _NaeraBillingService_UpdateBiller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBillerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NaeraBillingServiceServer).UpdateBiller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.NaeraBillingService/UpdateBiller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NaeraBillingServiceServer).UpdateBiller(ctx, req.(*UpdateBillerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NaeraBillingService_GetBillerBills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBillerBillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NaeraBillingServiceServer).GetBillerBills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.NaeraBillingService/GetBillerBills",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NaeraBillingServiceServer).GetBillerBills(ctx, req.(*GetBillerBillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NaeraBillingService_CreateBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Bill)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NaeraBillingServiceServer).CreateBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.NaeraBillingService/CreateBill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NaeraBillingServiceServer).CreateBill(ctx, req.(*Bill))
	}
	return interceptor(ctx, in, info, handler)
}

func _NaeraBillingService_FindBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Bill)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NaeraBillingServiceServer).FindBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.NaeraBillingService/FindBill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NaeraBillingServiceServer).FindBill(ctx, req.(*Bill))
	}
	return interceptor(ctx, in, info, handler)
}

func _NaeraBillingService_UpdateBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NaeraBillingServiceServer).UpdateBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.NaeraBillingService/UpdateBill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NaeraBillingServiceServer).UpdateBill(ctx, req.(*UpdateBillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NaeraBillingService_GetBillCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NaeraBillingServiceServer).GetBillCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.NaeraBillingService/GetBillCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NaeraBillingServiceServer).GetBillCategories(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NaeraBillingService_CreateBillCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BillCategory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NaeraBillingServiceServer).CreateBillCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.NaeraBillingService/CreateBillCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NaeraBillingServiceServer).CreateBillCategory(ctx, req.(*BillCategory))
	}
	return interceptor(ctx, in, info, handler)
}

func _NaeraBillingService_FindBillCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BillCategory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NaeraBillingServiceServer).FindBillCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.NaeraBillingService/FindBillCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NaeraBillingServiceServer).FindBillCategory(ctx, req.(*BillCategory))
	}
	return interceptor(ctx, in, info, handler)
}

func _NaeraBillingService_UpdateBillCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBillCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NaeraBillingServiceServer).UpdateBillCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.NaeraBillingService/UpdateBillCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NaeraBillingServiceServer).UpdateBillCategory(ctx, req.(*UpdateBillCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NaeraBillingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "models.NaeraBillingService",
	HandlerType: (*NaeraBillingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBiller",
			Handler:    _NaeraBillingService_CreateBiller_Handler,
		},
		{
			MethodName: "FindBiller",
			Handler:    _NaeraBillingService_FindBiller_Handler,
		},
		{
			MethodName: "UpdateBiller",
			Handler:    _NaeraBillingService_UpdateBiller_Handler,
		},
		{
			MethodName: "GetBillerBills",
			Handler:    _NaeraBillingService_GetBillerBills_Handler,
		},
		{
			MethodName: "CreateBill",
			Handler:    _NaeraBillingService_CreateBill_Handler,
		},
		{
			MethodName: "FindBill",
			Handler:    _NaeraBillingService_FindBill_Handler,
		},
		{
			MethodName: "UpdateBill",
			Handler:    _NaeraBillingService_UpdateBill_Handler,
		},
		{
			MethodName: "GetBillCategories",
			Handler:    _NaeraBillingService_GetBillCategories_Handler,
		},
		{
			MethodName: "CreateBillCategory",
			Handler:    _NaeraBillingService_CreateBillCategory_Handler,
		},
		{
			MethodName: "FindBillCategory",
			Handler:    _NaeraBillingService_FindBillCategory_Handler,
		},
		{
			MethodName: "UpdateBillCategory",
			Handler:    _NaeraBillingService_UpdateBillCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "models/v1/billing.proto",
}
