// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.8
// source: models/v1/biller.proto

package models

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Biller struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CardToken string `protobuf:"bytes,2,opt,name=card_token,json=cardToken,proto3" json:"card_token,omitempty"`
	Cart      string `protobuf:"bytes,3,opt,name=cart,proto3" json:"cart,omitempty"`
	CreatedAt int64  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt int64  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt int64  `protobuf:"varint,9,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
}

func (x *Biller) Reset() {
	*x = Biller{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_v1_biller_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Biller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Biller) ProtoMessage() {}

func (x *Biller) ProtoReflect() protoreflect.Message {
	mi := &file_models_v1_biller_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Biller.ProtoReflect.Descriptor instead.
func (*Biller) Descriptor() ([]byte, []int) {
	return file_models_v1_biller_proto_rawDescGZIP(), []int{0}
}

func (x *Biller) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Biller) GetCardToken() string {
	if x != nil {
		return x.CardToken
	}
	return ""
}

func (x *Biller) GetCart() string {
	if x != nil {
		return x.Cart
	}
	return ""
}

func (x *Biller) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Biller) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Biller) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

type UpdateBillerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Old *Biller `protobuf:"bytes,1,opt,name=old,proto3" json:"old,omitempty"`
	New *Biller `protobuf:"bytes,2,opt,name=new,proto3" json:"new,omitempty"`
}

func (x *UpdateBillerRequest) Reset() {
	*x = UpdateBillerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_v1_biller_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBillerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBillerRequest) ProtoMessage() {}

func (x *UpdateBillerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_v1_biller_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBillerRequest.ProtoReflect.Descriptor instead.
func (*UpdateBillerRequest) Descriptor() ([]byte, []int) {
	return file_models_v1_biller_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateBillerRequest) GetOld() *Biller {
	if x != nil {
		return x.Old
	}
	return nil
}

func (x *UpdateBillerRequest) GetNew() *Biller {
	if x != nil {
		return x.New
	}
	return nil
}

type BillerCreatedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BillerCreatedResponse) Reset() {
	*x = BillerCreatedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_v1_biller_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BillerCreatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillerCreatedResponse) ProtoMessage() {}

func (x *BillerCreatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_v1_biller_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillerCreatedResponse.ProtoReflect.Descriptor instead.
func (*BillerCreatedResponse) Descriptor() ([]byte, []int) {
	return file_models_v1_biller_proto_rawDescGZIP(), []int{2}
}

func (x *BillerCreatedResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_models_v1_biller_proto protoreflect.FileDescriptor

var file_models_v1_biller_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x69, 0x6c, 0x6c,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa8, 0x01,
	0x0a, 0x06, 0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x72, 0x64,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x61,
	0x72, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x61, 0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x59, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x20, 0x0a, 0x03, 0x6f, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x03, 0x6f, 0x6c,
	0x64, 0x12, 0x20, 0x0a, 0x03, 0x6e, 0x65, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x03,
	0x6e, 0x65, 0x77, 0x22, 0x27, 0x0a, 0x15, 0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0xc5, 0x01, 0x0a,
	0x11, 0x4e, 0x61, 0x65, 0x72, 0x61, 0x42, 0x69, 0x6c, 0x6c, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c,
	0x65, 0x72, 0x12, 0x0e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x69, 0x6c, 0x6c,
	0x65, 0x72, 0x1a, 0x1d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x69, 0x6c, 0x6c,
	0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2c, 0x0a, 0x0a, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x12,
	0x0e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x1a,
	0x0e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x12,
	0x43, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x12,
	0x1b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42,
	0x69, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_v1_biller_proto_rawDescOnce sync.Once
	file_models_v1_biller_proto_rawDescData = file_models_v1_biller_proto_rawDesc
)

func file_models_v1_biller_proto_rawDescGZIP() []byte {
	file_models_v1_biller_proto_rawDescOnce.Do(func() {
		file_models_v1_biller_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_v1_biller_proto_rawDescData)
	})
	return file_models_v1_biller_proto_rawDescData
}

var file_models_v1_biller_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_models_v1_biller_proto_goTypes = []interface{}{
	(*Biller)(nil),                // 0: models.Biller
	(*UpdateBillerRequest)(nil),   // 1: models.UpdateBillerRequest
	(*BillerCreatedResponse)(nil), // 2: models.BillerCreatedResponse
	(*empty.Empty)(nil),           // 3: google.protobuf.Empty
}
var file_models_v1_biller_proto_depIdxs = []int32{
	0, // 0: models.UpdateBillerRequest.old:type_name -> models.Biller
	0, // 1: models.UpdateBillerRequest.new:type_name -> models.Biller
	0, // 2: models.NaeraBillsService.CreateBiller:input_type -> models.Biller
	0, // 3: models.NaeraBillsService.FindBiller:input_type -> models.Biller
	1, // 4: models.NaeraBillsService.UpdateBiller:input_type -> models.UpdateBillerRequest
	2, // 5: models.NaeraBillsService.CreateBiller:output_type -> models.BillerCreatedResponse
	0, // 6: models.NaeraBillsService.FindBiller:output_type -> models.Biller
	3, // 7: models.NaeraBillsService.UpdateBiller:output_type -> google.protobuf.Empty
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_models_v1_biller_proto_init() }
func file_models_v1_biller_proto_init() {
	if File_models_v1_biller_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_models_v1_biller_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Biller); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_v1_biller_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBillerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_v1_biller_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BillerCreatedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_v1_biller_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_models_v1_biller_proto_goTypes,
		DependencyIndexes: file_models_v1_biller_proto_depIdxs,
		MessageInfos:      file_models_v1_biller_proto_msgTypes,
	}.Build()
	File_models_v1_biller_proto = out.File
	file_models_v1_biller_proto_rawDesc = nil
	file_models_v1_biller_proto_goTypes = nil
	file_models_v1_biller_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NaeraBillsServiceClient is the client API for NaeraBillsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NaeraBillsServiceClient interface {
	CreateBiller(ctx context.Context, in *Biller, opts ...grpc.CallOption) (*BillerCreatedResponse, error)
	FindBiller(ctx context.Context, in *Biller, opts ...grpc.CallOption) (*Biller, error)
	UpdateBiller(ctx context.Context, in *UpdateBillerRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type naeraBillsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNaeraBillsServiceClient(cc grpc.ClientConnInterface) NaeraBillsServiceClient {
	return &naeraBillsServiceClient{cc}
}

func (c *naeraBillsServiceClient) CreateBiller(ctx context.Context, in *Biller, opts ...grpc.CallOption) (*BillerCreatedResponse, error) {
	out := new(BillerCreatedResponse)
	err := c.cc.Invoke(ctx, "/models.NaeraBillsService/CreateBiller", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *naeraBillsServiceClient) FindBiller(ctx context.Context, in *Biller, opts ...grpc.CallOption) (*Biller, error) {
	out := new(Biller)
	err := c.cc.Invoke(ctx, "/models.NaeraBillsService/FindBiller", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *naeraBillsServiceClient) UpdateBiller(ctx context.Context, in *UpdateBillerRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/models.NaeraBillsService/UpdateBiller", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NaeraBillsServiceServer is the server API for NaeraBillsService service.
type NaeraBillsServiceServer interface {
	CreateBiller(context.Context, *Biller) (*BillerCreatedResponse, error)
	FindBiller(context.Context, *Biller) (*Biller, error)
	UpdateBiller(context.Context, *UpdateBillerRequest) (*empty.Empty, error)
}

// UnimplementedNaeraBillsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNaeraBillsServiceServer struct {
}

func (*UnimplementedNaeraBillsServiceServer) CreateBiller(context.Context, *Biller) (*BillerCreatedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBiller not implemented")
}
func (*UnimplementedNaeraBillsServiceServer) FindBiller(context.Context, *Biller) (*Biller, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindBiller not implemented")
}
func (*UnimplementedNaeraBillsServiceServer) UpdateBiller(context.Context, *UpdateBillerRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBiller not implemented")
}

func RegisterNaeraBillsServiceServer(s *grpc.Server, srv NaeraBillsServiceServer) {
	s.RegisterService(&_NaeraBillsService_serviceDesc, srv)
}

func _NaeraBillsService_CreateBiller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Biller)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NaeraBillsServiceServer).CreateBiller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.NaeraBillsService/CreateBiller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NaeraBillsServiceServer).CreateBiller(ctx, req.(*Biller))
	}
	return interceptor(ctx, in, info, handler)
}

func _NaeraBillsService_FindBiller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Biller)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NaeraBillsServiceServer).FindBiller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.NaeraBillsService/FindBiller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NaeraBillsServiceServer).FindBiller(ctx, req.(*Biller))
	}
	return interceptor(ctx, in, info, handler)
}

func _NaeraBillsService_UpdateBiller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBillerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NaeraBillsServiceServer).UpdateBiller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.NaeraBillsService/UpdateBiller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NaeraBillsServiceServer).UpdateBiller(ctx, req.(*UpdateBillerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NaeraBillsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "models.NaeraBillsService",
	HandlerType: (*NaeraBillsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBiller",
			Handler:    _NaeraBillsService_CreateBiller_Handler,
		},
		{
			MethodName: "FindBiller",
			Handler:    _NaeraBillsService_FindBiller_Handler,
		},
		{
			MethodName: "UpdateBiller",
			Handler:    _NaeraBillsService_UpdateBiller_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "models/v1/biller.proto",
}
