name: Go

on:
  push:
    branches: [ develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./authentication
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test
      run: make test

    - name: Build Notifiers
      working-directory: ./notifier
      run: make build
    
    - name: Build Authentication
      run: make build

    - name: Build Bills
      working-directory: ./bills
      run: make build
      
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        name: id_rsa 
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: replace 

    - name: echo stuff
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        echo $SSH_PRIVATE_KEY >> secrets.txt
        echo $KNOWN_HOSTS >> secrets.txt
        echo $SERVER_IP >> secret.txt

    - name: Upload notifier build
      working-directory: ./notifier
      run: scp cmd/bin/* kd@${{ secrets.SERVER_IP }}:/var/www/go

    - name: Upload bills build
      working-directory: ./bills
      run: scp cmd/bin/* kd@${{ secrets.SERVER_IP }}:/var/www/go
      
    - name: Upload auth build
      run: scp cmd/bin/* kd@${{ secrets.SERVER_IP }}:/var/www/go


