name: Go

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./authentication
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test
      run: make test
    
    - name: Build
      run: make build
      
    - name: deploy file to server
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: 'kd'
        server: '${{ secrets.SERVER_IP }}'
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        local_path: './cmd/bin/*'
        remote_path: '/var/www/go'
